### ISSUE TITLE
Disable download external resources by default  

### ISSUE THREAD

**Issue by jukzi** [eclipse-wildwebdeveloper/wildwebdeveloper#1289]
For privacy reasons please do not contact external resources without asking the user before. 
I.e. disable option "Download external resources like referenced DTD, XSD"  by default.

Optional gold plating: Let the user maintain a list of trusted hosts or resources.

**Comment by angelozerr** [comment]
> For privacy reasons please do not contact external resources without asking the user before.
I.e. disable option "Download external resources like referenced DTD, XSD" by default.

Indeed WWD should do that, I would like to add that lemminx takes care of this settings. It disable the download, but for helping the user to understand why it doesn't work (because in Eclipse IDE there is no trust behavior for workspace like vscode or IJ), lemminx reports an error where the XSD, DTD cannot be downloaded. And more it provides a quickfix which provide the capability to the user to download only the XSD, DTD which is forbidden:

![image](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/1932211/ed578d84-76a8-47ad-9702-1b0bb5da14c1) 

> Optional gold plating: Let the user maintain a list of trusted hosts or resources.

please create an issue on lemminx project.
