### ISSUE TITLE
"Run/Debug As" > "Node program" for Typescript file may launch wrong Javascript file

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse-wildwebdeveloper/wildwebdeveloper#1366]
Depending on the layout of project files & `tsconfig.json`, trying to run a Typescript file may fail to find the correct path of that file's associated Javascript file, and thus fail to run the file.

For example, excluding `node_modules` and lockfiles, I have a project directory of:
```
.
├── lib
│   ├── main.js
│   └── main.js.map
├── package.json
├── src
│   └── main.ts
└── tsconfig.json
```
and a `tsconfig.json` of
```
{
	"extends": "@tsconfig/node16/tsconfig.json",
	"compilerOptions": {
		"sourceMap": true,
		"outDir": "lib",
		"rootDir": "src",
		"lib": ["dom", "es2020"]
	}
}
```
When trying to run `./src/main.ts`, WWD should run `./lib/main.js`, but it instead launches `./lib/src/main.js`, which doesn't exist.

It seems that WWD constructs the path of the Javascript file to run as
```
jsToRun=${project-directory}/${outDir}/${project-relative-path-to-ts-file/.ts/.js}
```
but it should be
```
trueDir=${project-relative-path-to-ts-file/${rootDir}/${outDir}}
jsToRun=${project-directory}/${trueDir/.ts/.js}}
```
where I've used Bash to illustrate the path construction.

**Comment by mickaelistria** [comment]
Would you be able to provide a PR illustrating this in a test case and fixing it?
Note that in https://github.com/microsoft/vscode-js-debug/issues/1838 , the maintainers of vscode-js-debug mention that the ts -> js resolution should be handled on the adapter end, so we could in theory pass directly the path to the .ts file. But I didn't manage to get it to work earlier.
So if you're willing to put workforce on this topic, instead of fixing how Wild Web Developer resolves the path, it could be more interesting to make the DAP resolution work and drop the resolution in Wild Web Developer.

**Comment by AndrewFerr** [comment]
Sounds like a plan.  I'll give it a try.

**Comment by mickaelistria** [comment]
Submitted https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1368 as a quick-fix, but that doesn't mean we can't do better by using the debug adapter feature directly ;)

**Comment by AndrewFerr** [comment]
@wesleybl Yes, the debug should be in the TS file, or in your case, the source JS file instead of the Webpack-generated JS file.

Did you enable source maps in your Webpack config?  If so, then perhaps the debug adapter is aware of only TS->JS mappings.

**Comment by AndrewFerr** [comment]
> Submitted #1368 as a quick-fix, but that doesn't mean we can't do better by using the debug adapter feature directly ;)

Downloaded the snapshot & verified that the quick fix works, thanks!
