### ISSUE TITLE
Clarification on plugin startup and class loading

### ISSUE THREAD

**Issue by kal-el11** [eclipse-wildwebdeveloper/wildwebdeveloper#1498]
I have written a plugin A which extends lemminx extension point "org.eclipse.wildwebdeveloper.xml.lemminxExtension". I hope xml language server is activated when an xml file is opened in editor.
```html
<jar path="mydummy.jar" />
``` 

The language server loads the classes from the jar I have mentioned in the extension point. The language server runs as a separate process. 
1) Is it possible to activate the xml language server before opening a xml file? 
2) Can the plugin A access the classes from the jars mentioned in lemminx extension point? 
Please clarify.

**Comment by mickaelistria** [comment]
> Is it possible to activate the xml language server before opening a xml file?

You will most likely need your plugin to setup an `org.eclipse.ui.startup` extension that would cause the LS to startup (by calling it from registry).

> Can the plugin A access the classes from the jars mentioned in lemminx extension point?

Yes, it can probably work as all jars will be loaded in the same classloader.

**Comment by angelozerr** [comment]
@kal-el11 why do you want to start the xml lemminx ls when eclipse ide has started ?

Perhaps it is to support workspace symbols because with this feature you dont need to open any file.

IMHO I think lsp4e should provide an extension point to start ls when ide has started.

Lsp4e could loup for each ls server définition and use this extension point to know if ls must be started.

Vscode has this kind of feature which is very Nice. This feature is not linked to lsp support but to the start of the vscode extension

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.
