### ISSUE TITLE
Release 1.3.7 for 2024-09

### ISSUE THREAD

**Issue by merks** [eclipse-wildwebdeveloper/wildwebdeveloper#1651]
The latest release is the following and that's contributed to SimRel

https://download.eclipse.org/wildwebdeveloper/releases/1.3.6/

I would like there to be a 1.3.7 release for 2024-09.  

What can I do to help enable this?  Once a p2 URL exists, I can definitely do the rest for you...

**Comment by vrubezhny** [comment]
Currently we cannot release due to the Vue.js language server problem (due to its incompatibility with latest Volar Language Server: https://github.com/vuejs/language-tools/issues/4707 - Vue.js has it fixed in its master branch, but we still have to wait for the fix to be released and published). I have no any any estimation on when the Vue.js release will take place. 

Once Vue.js problem is fixed - it should be OK to release 1.37.
One more thing is that we need to make sure that WWD + Lemminx-Maven (Lemminx) + M2E Core are fully compatible when installed together after WWD 1.37 is released.

**Comment by merks** [comment]
@vrubezhny  

Thanks for the update!  🙏 

I've actually been testing the combination of m2e with the latest WWD staging build in order to make use of this PR:

https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1644

I've seen no noticeable problems.

**Comment by vrubezhny** [comment]
Good to know.

The mentioned Vue.js problem appears when trying to work with typescript/javascript projects and may potentially make WWD to freeze/hang up  during the LS initialization - which, imho, blocks us from releasing it until Vue.js is fixed.

**Comment by merks** [comment]
I see that 1.3.7 is available and has been contribute to SimRel:

https://download.eclipse.org/wildwebdeveloper/releases/1.3.7/

Thank you.   🏆
